### ISSUE TITLE
Support Cabal >= 2.2

### ISSUE THREAD

**Issue by ElvishJerricco** [spinda/liquidhaskell-cabal#11]
Trying to build with Cabal 2.2:

```
[1 of 1] Compiling LiquidHaskell.Cabal ( src/LiquidHaskell/Cabal.hs, dist/build/LiquidHaskell/Cabal.o )

src/LiquidHaskell/Cabal.hs:32:1: error:
    Could not find module ‘Distribution.PackageDescription.Parse’
    Perhaps you meant
      Distribution.PackageDescription.Parsec (from Cabal-2.2.0.1)
      Distribution.PackageDescription.Check (from Cabal-2.2.0.1)
      Distribution.PackageDescription.Quirks (from Cabal-2.2.0.1)
    Use -v to see a list of the files searched for.
   |
32 | import Distribution.PackageDescription.Parse
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by spinda** [comment]
Hi @ElvishJerricco, thanks for submitting this. I haven't been paying a lot of attention to Liquid Haskell lately, but I'll set some time aside this weekend to get this package back in working order.

**Comment by spinda** [comment]
Published `liquidhaskell-cabal-0.2.0.0` which should address this.
